<?php

namespace linkphp\addons;

use framework\Controller as FrameworkController;

class Controller extends FrameworkController
{

    public function display($template)
    {
        return parent::display($template); // TODO: Change the autogenerated stub
    }

    public function assign($name, $value = null)
    {
        return parent::assign($name, $value); // TODO: Change the autogenerated stub
    }

    public function redirect()
    {
        parent::redirect(); // TODO: Change the autogenerated stub
    }

    public function view($template, $data = null)
    {
        return parent::view($template, $data); // TODO: Change the autogenerated stub
    }

}